### ISSUE TITLE
[BUG]Невозможность запустить локалку

### ISSUE THREAD

**Issue by Kirillezis** [Lambda-13/rustest#89]
При запуске локалки, в любых режимах и на любых версиях, не запускается чат, при попытке починить, ничего не происходит. Так же при попытке сыграть так, встречаюсь с проблемой белых окон.
Очистка кеша\обновление\переустановка и прочее не помогло.

**Comment by SanecMan** [comment]
Ошибки скрины будут?

**Comment by Kirillezis** [comment]
> Ошибки скрины будут?

Дело в том что ошибок он как раз таки и не выдает

**Comment by Kirillezis** [comment]
![Uploading image.png…]()

**Comment by Kirillezis** [comment]
![image](https://user-images.githubusercontent.com/105250646/236894252-91b626ec-ed22-4d15-9693-1463b8c8d17b.png)
![image](https://user-images.githubusercontent.com/105250646/236894273-4ab9a8fd-5f9c-441c-bbfe-1f91323f81a0.png)
![image](https://user-images.githubusercontent.com/105250646/236894314-55dbad59-45b3-4829-b57d-6a13ca0c812f.png)
![image](https://user-images.githubusercontent.com/105250646/236894430-602b7dad-3789-4d75-b72d-3fdfb43fb6a7.png)

**Comment by SanecMan** [comment]
> > Ошибки скрины будут?
> 
> Дело в том что ошибок он как раз таки и не выдает

Есть три решения данной проблемы:
1. * `rustest\bin\clean.cmd` очистит всю компиляцию тгуи
    * `rustest\bin\build.cmd` скомпилирует заного билд
   ---
2. * Перезагрузка компьютера или скачивание билда заного
---
3. * `OOC - Fix Chat` повторить два раза
---
Лично мне помогал второй и третий вариант

**Comment by Kirillezis** [comment]
![image](https://user-images.githubusercontent.com/105250646/236895857-3a59f1ae-994d-4afd-9d20-565935fe9fe5.png)

**Comment by SanecMan** [comment]
> ![image](https://user-images.githubusercontent.com/105250646/236895857-3a59f1ae-994d-4afd-9d20-565935fe9fe5.png)

Ошибка в не установленном NodeJS, установить его можно [тут](https://nodejs.org/en/download). Затем после установки запускай build.cmd в папке bin или build.bat в корневой папке сборки, запускай DreamDaemon и играй. Подробнее об этом и о том как запускать сборки станции можно почитать [вот тут](https://hackmd.io/QtFabOB7Th2zPiHeyCKbNw). Так-же советую посетить кодербус русских программистов в [Дискорде](https://discord.gg/fRsn7RxdQp).

**Comment by SanecMan** [comment]
Думаю проблема была решена. Если остались вопросы обращаться в Дискорд сюда sanecman#2139
